name: Python Docker Push
on: 
  push: 
    branches: [ "master" ]
  
jobs:
  python-Test:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@v2    
          
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV
        if: github.run_number != ''

      - name: Count commits
        id: count-commits
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
        if: github.run_number == ''

      - name: Set IMAGE_TAG with commit count
        run: echo "IMAGE_TAG=v${{ env.COMMIT_COUNT }}" >> $GITHUB_ENV
        if: github.run_number == ''

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO}}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
